#pragma checksum "..\..\..\MainWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "EF5CFA0C0F88D9ED818177746D4A57FF89D53080"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NakisCAD.App;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace NakisCAD.App {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 199 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtZoomLevel;
        
        #line default
        #line hidden
        
        
        #line 315 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtDesignName;
        
        #line default
        #line hidden
        
        
        #line 318 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtTotalStitches;
        
        #line default
        #line hidden
        
        
        #line 321 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtColorChanges;
        
        #line default
        #line hidden
        
        
        #line 324 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtWidth;
        
        #line default
        #line hidden
        
        
        #line 327 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtHeight;
        
        #line default
        #line hidden
        
        
        #line 339 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtNormalCount;
        
        #line default
        #line hidden
        
        
        #line 347 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtJumpCount;
        
        #line default
        #line hidden
        
        
        #line 355 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtColorChangeCount;
        
        #line default
        #line hidden
        
        
        #line 363 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtEndCount;
        
        #line default
        #line hidden
        
        
        #line 369 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtFilePath;
        
        #line default
        #line hidden
        
        
        #line 380 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListView lstColorObjects;
        
        #line default
        #line hidden
        
        
        #line 406 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbFabric;
        
        #line default
        #line hidden
        
        
        #line 415 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtAlpha;
        
        #line default
        #line hidden
        
        
        #line 418 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBeta;
        
        #line default
        #line hidden
        
        
        #line 425 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtStitchLength;
        
        #line default
        #line hidden
        
        
        #line 434 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtDensity;
        
        #line default
        #line hidden
        
        
        #line 441 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtPullComp;
        
        #line default
        #line hidden
        
        
        #line 444 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtPushFactor;
        
        #line default
        #line hidden
        
        
        #line 451 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtJumpThreshold;
        
        #line default
        #line hidden
        
        
        #line 454 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbTrimCount;
        
        #line default
        #line hidden
        
        
        #line 476 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock canvasPlaceholder;
        
        #line default
        #line hidden
        
        
        #line 482 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas designCanvas;
        
        #line default
        #line hidden
        
        
        #line 491 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform canvasScale;
        
        #line default
        #line hidden
        
        
        #line 492 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.TranslateTransform canvasTranslate;
        
        #line default
        #line hidden
        
        
        #line 499 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas rulerTop;
        
        #line default
        #line hidden
        
        
        #line 513 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer logScroll;
        
        #line default
        #line hidden
        
        
        #line 514 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtLog;
        
        #line default
        #line hidden
        
        
        #line 531 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbStitchType;
        
        #line default
        #line hidden
        
        
        #line 540 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtStitchWidth;
        
        #line default
        #line hidden
        
        
        #line 543 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtObjDensity;
        
        #line default
        #line hidden
        
        
        #line 546 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtStitchAngle;
        
        #line default
        #line hidden
        
        
        #line 560 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtPosX;
        
        #line default
        #line hidden
        
        
        #line 562 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtPosY;
        
        #line default
        #line hidden
        
        
        #line 566 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtObjWidth;
        
        #line default
        #line hidden
        
        
        #line 569 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtObjHeight;
        
        #line default
        #line hidden
        
        
        #line 575 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkSmartCorner;
        
        #line default
        #line hidden
        
        
        #line 576 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkMiterCorner;
        
        #line default
        #line hidden
        
        
        #line 577 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkLapJoint;
        
        #line default
        #line hidden
        
        
        #line 578 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkStaggeredPitch;
        
        #line default
        #line hidden
        
        
        #line 584 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkPullComp;
        
        #line default
        #line hidden
        
        
        #line 585 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkPushComp;
        
        #line default
        #line hidden
        
        
        #line 586 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkUnderlay;
        
        #line default
        #line hidden
        
        
        #line 587 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkSolvy;
        
        #line default
        #line hidden
        
        
        #line 593 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkMicroStitchFilter;
        
        #line default
        #line hidden
        
        
        #line 594 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkAutoTieOff;
        
        #line default
        #line hidden
        
        
        #line 595 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkAutoTrim;
        
        #line default
        #line hidden
        
        
        #line 596 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkDeltaSplit;
        
        #line default
        #line hidden
        
        
        #line 604 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtSearch;
        
        #line default
        #line hidden
        
        
        #line 609 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListView lstStitches;
        
        #line default
        #line hidden
        
        
        #line 634 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl threadPalette;
        
        #line default
        #line hidden
        
        
        #line 660 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtCustomColor;
        
        #line default
        #line hidden
        
        
        #line 679 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtStatus;
        
        #line default
        #line hidden
        
        
        #line 680 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtCoords;
        
        #line default
        #line hidden
        
        
        #line 681 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtStitchInfo;
        
        #line default
        #line hidden
        
        
        #line 682 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtZoomStatus;
        
        #line default
        #line hidden
        
        
        #line 692 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel colorBar;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.29.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/NakisCAD.App;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.29.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 116 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnNewProject);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 117 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnOpenDst);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 119 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnLoadImage);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 120 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnAutoDigitize);
            
            #line default
            #line hidden
            return;
            case 5:
            
            #line 124 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnSave);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 125 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnSaveAs);
            
            #line default
            #line hidden
            return;
            case 7:
            
            #line 126 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnCreateSample);
            
            #line default
            #line hidden
            return;
            case 8:
            
            #line 128 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnExit);
            
            #line default
            #line hidden
            return;
            case 9:
            
            #line 137 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnToggleTrueView);
            
            #line default
            #line hidden
            return;
            case 10:
            
            #line 138 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnToggleStitches);
            
            #line default
            #line hidden
            return;
            case 11:
            
            #line 139 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnToggleOutlines);
            
            #line default
            #line hidden
            return;
            case 12:
            
            #line 142 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnToggleGrid);
            
            #line default
            #line hidden
            return;
            case 13:
            
            #line 145 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnZoomIn);
            
            #line default
            #line hidden
            return;
            case 14:
            
            #line 146 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnZoomOut);
            
            #line default
            #line hidden
            return;
            case 15:
            
            #line 147 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnZoomFit);
            
            #line default
            #line hidden
            return;
            case 16:
            
            #line 148 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnZoom100);
            
            #line default
            #line hidden
            return;
            case 17:
            
            #line 151 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnDstAnalysis);
            
            #line default
            #line hidden
            return;
            case 18:
            
            #line 152 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnCountStitches);
            
            #line default
            #line hidden
            return;
            case 19:
            
            #line 153 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnDensityMap);
            
            #line default
            #line hidden
            return;
            case 20:
            
            #line 155 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnSettings);
            
            #line default
            #line hidden
            return;
            case 21:
            
            #line 161 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnMachineConnect);
            
            #line default
            #line hidden
            return;
            case 22:
            
            #line 167 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnAbout);
            
            #line default
            #line hidden
            return;
            case 23:
            
            #line 176 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnNewProject);
            
            #line default
            #line hidden
            return;
            case 24:
            
            #line 177 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnOpenDst);
            
            #line default
            #line hidden
            return;
            case 25:
            
            #line 178 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnSave);
            
            #line default
            #line hidden
            return;
            case 26:
            
            #line 190 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnToggleTrueView);
            
            #line default
            #line hidden
            return;
            case 27:
            
            #line 191 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnToggleGrid);
            
            #line default
            #line hidden
            return;
            case 28:
            
            #line 193 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnZoomIn);
            
            #line default
            #line hidden
            return;
            case 29:
            
            #line 194 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnZoomOut);
            
            #line default
            #line hidden
            return;
            case 30:
            
            #line 195 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnZoomFit);
            
            #line default
            #line hidden
            return;
            case 31:
            
            #line 196 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnZoom100);
            
            #line default
            #line hidden
            return;
            case 32:
            this.txtZoomLevel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 33:
            
            #line 229 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnToolSelect);
            
            #line default
            #line hidden
            return;
            case 34:
            
            #line 239 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnLoadImage);
            
            #line default
            #line hidden
            return;
            case 35:
            
            #line 242 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnAutoDigitize);
            
            #line default
            #line hidden
            return;
            case 36:
            
            #line 249 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnDigitizeOpen);
            
            #line default
            #line hidden
            return;
            case 37:
            
            #line 252 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnDigitizeClosed);
            
            #line default
            #line hidden
            return;
            case 38:
            
            #line 255 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnDigitizeRect);
            
            #line default
            #line hidden
            return;
            case 39:
            
            #line 258 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnDigitizeCircle);
            
            #line default
            #line hidden
            return;
            case 40:
            
            #line 261 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnDigitizeFreehand);
            
            #line default
            #line hidden
            return;
            case 41:
            
            #line 264 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnDigitizeSatinCol);
            
            #line default
            #line hidden
            return;
            case 42:
            this.txtDesignName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 43:
            this.txtTotalStitches = ((System.Windows.Controls.TextBox)(target));
            return;
            case 44:
            this.txtColorChanges = ((System.Windows.Controls.TextBox)(target));
            return;
            case 45:
            this.txtWidth = ((System.Windows.Controls.TextBox)(target));
            return;
            case 46:
            this.txtHeight = ((System.Windows.Controls.TextBox)(target));
            return;
            case 47:
            this.txtNormalCount = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 48:
            this.txtJumpCount = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 49:
            this.txtColorChangeCount = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 50:
            this.txtEndCount = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 51:
            this.txtFilePath = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 52:
            this.lstColorObjects = ((System.Windows.Controls.ListView)(target));
            return;
            case 53:
            this.cmbFabric = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 54:
            this.txtAlpha = ((System.Windows.Controls.TextBox)(target));
            return;
            case 55:
            this.txtBeta = ((System.Windows.Controls.TextBox)(target));
            return;
            case 56:
            this.txtStitchLength = ((System.Windows.Controls.TextBox)(target));
            return;
            case 57:
            this.txtDensity = ((System.Windows.Controls.TextBox)(target));
            return;
            case 58:
            this.txtPullComp = ((System.Windows.Controls.TextBox)(target));
            return;
            case 59:
            this.txtPushFactor = ((System.Windows.Controls.TextBox)(target));
            return;
            case 60:
            this.txtJumpThreshold = ((System.Windows.Controls.TextBox)(target));
            return;
            case 61:
            this.cmbTrimCount = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 62:
            this.canvasPlaceholder = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 63:
            this.designCanvas = ((System.Windows.Controls.Canvas)(target));
            
            #line 483 "..\..\..\MainWindow.xaml"
            this.designCanvas.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.Canvas_MouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 484 "..\..\..\MainWindow.xaml"
            this.designCanvas.MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.Canvas_MouseLeftButtonUp);
            
            #line default
            #line hidden
            
            #line 485 "..\..\..\MainWindow.xaml"
            this.designCanvas.MouseMove += new System.Windows.Input.MouseEventHandler(this.Canvas_MouseMove);
            
            #line default
            #line hidden
            
            #line 486 "..\..\..\MainWindow.xaml"
            this.designCanvas.MouseWheel += new System.Windows.Input.MouseWheelEventHandler(this.Canvas_MouseWheel);
            
            #line default
            #line hidden
            
            #line 487 "..\..\..\MainWindow.xaml"
            this.designCanvas.MouseRightButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.Canvas_MouseRightButtonDown);
            
            #line default
            #line hidden
            
            #line 488 "..\..\..\MainWindow.xaml"
            this.designCanvas.MouseRightButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.Canvas_MouseRightButtonUp);
            
            #line default
            #line hidden
            return;
            case 64:
            this.canvasScale = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 65:
            this.canvasTranslate = ((System.Windows.Media.TranslateTransform)(target));
            return;
            case 66:
            this.rulerTop = ((System.Windows.Controls.Canvas)(target));
            return;
            case 67:
            
            #line 510 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnClearLog);
            
            #line default
            #line hidden
            return;
            case 68:
            this.logScroll = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 69:
            this.txtLog = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 70:
            this.cmbStitchType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 71:
            this.txtStitchWidth = ((System.Windows.Controls.TextBox)(target));
            return;
            case 72:
            this.txtObjDensity = ((System.Windows.Controls.TextBox)(target));
            return;
            case 73:
            this.txtStitchAngle = ((System.Windows.Controls.TextBox)(target));
            return;
            case 74:
            this.txtPosX = ((System.Windows.Controls.TextBox)(target));
            return;
            case 75:
            this.txtPosY = ((System.Windows.Controls.TextBox)(target));
            return;
            case 76:
            this.txtObjWidth = ((System.Windows.Controls.TextBox)(target));
            return;
            case 77:
            this.txtObjHeight = ((System.Windows.Controls.TextBox)(target));
            return;
            case 78:
            this.chkSmartCorner = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 79:
            this.chkMiterCorner = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 80:
            this.chkLapJoint = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 81:
            this.chkStaggeredPitch = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 82:
            this.chkPullComp = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 83:
            this.chkPushComp = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 84:
            this.chkUnderlay = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 85:
            this.chkSolvy = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 86:
            this.chkMicroStitchFilter = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 87:
            this.chkAutoTieOff = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 88:
            this.chkAutoTrim = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 89:
            this.chkDeltaSplit = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 90:
            this.txtSearch = ((System.Windows.Controls.TextBox)(target));
            
            #line 607 "..\..\..\MainWindow.xaml"
            this.txtSearch.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.OnSearchChanged);
            
            #line default
            #line hidden
            return;
            case 91:
            this.lstStitches = ((System.Windows.Controls.ListView)(target));
            
            #line 609 "..\..\..\MainWindow.xaml"
            this.lstStitches.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.OnStitchSelected);
            
            #line default
            #line hidden
            return;
            case 92:
            this.threadPalette = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 93:
            this.txtCustomColor = ((System.Windows.Controls.TextBox)(target));
            return;
            case 94:
            this.txtStatus = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 95:
            this.txtCoords = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 96:
            this.txtStitchInfo = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 97:
            this.txtZoomStatus = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 98:
            this.colorBar = ((System.Windows.Controls.StackPanel)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

